### ISSUE TITLE
We dont know how to style with vuetify the json schema generated form

### ISSUE THREAD

**Issue by jurra** [Hardocs/desktop-app#77]
# We have several options
1. We try to apply materialize css classes to the component: <https://materializecss.com/buttons.html>
2. We can alternatively just do hardcoded form with vuetify not using the form generator engine.

## My suggestion is the following
If the second one takes less time, do it first. On the other hand 1 provides us with validation, so lets try 1 first.

**Comment by DNature** [comment]
After experimenting with `materializecss`, I noticed that it comes with good default styling on major HTML tags like input. However, we cannot customize the looks and it doesn't look good because we don't have control over the generated form by JSON SCHEMA.

My take is that we should re-create the form with vuetify and a form validation library.

**Comment by jurra** [comment]
Take a look into this Divine: https://vuejsexamples.com/schema-based-form-generator-vue-js-2-0-component-based-on-vuetify/

**Comment by jurra** [comment]
Consider also this: https://github.com/koumoul-dev/vuetify-jsonschema-form

**Comment by DNature** [comment]
Okay. Also, look at this approach of form field validations <https://vijitail.dev/blog/form-validation-in-vue-using-yup>

**Comment by jurra** [comment]
Problem solved ;) Great job
